import 'package:get/get.dart';

class Translate extends Translations{
  @override
  Map<String, Map<String, String>> get keys => {

    "ar" : {
      "1" : "اختر لغتك المفضلة",
      "2" : "عربي",
      "3" : "إنجليزي",
      "4" : "مرحباً",
      "5" : "ابني نمط حياة صحي",
      "6" : "تتبع ما تأكله",
      "7" : "طعام",
      "8" : "تمرن في أي مكان",
      "9" : "صالة الألعاب الرياضية أو المنزل أو حتى الحديقة",
      "10" : "شارك الخبرة",
      "11" : "النشر والتعليق",
      "12" : "تسجيل الدخول",
      "13" : "إنشاء حساب",
      "14" : "مرحبًا بعودتك",
      "15" : "قم بتسجيل الدخول باستخدام بريدك الإلكتروني وكلمة المرور \nأو باستخدام وسائل التواصل الاجتماعي",
      "16" : "بريد إلكتروني",
      "17" : "أدخل بريدك الإلكتروني",
      "18" : "كلمة المرور",
      "19" : "أدخل كلمة المرور",
      "20" : "هل نسيت كلمة المرور؟",
      "21" : "ليس لديك حساب؟ ",
      "25" : "نحن سعداء لرؤيتك",
      "26" : "ابدأ الآن بإنشاء حسابك، أو استخدم ملفك الشخصي\nعلى وسائل التواصل الاجتماعي للتسجيل",
      "27" : "الاسم الاول",
      "28" : "أدخل اسمك الأول",
      "29" : "اسم عائلتك",
      "30" : "أدخل اسم عائلتك",
      "31" : "تأكيد كلمة المرور",
      "32" : "أدخل كلمة المرور مرة أخرى",
      "33" : "هل سبق لك التسجيل من قبل؟ ",
      "34" : "نسيت كلمة المرور",
      "35" : "إعادة تعيين كلمة المرور",
      "36" : "أدخل عنوان البريد الإلكتروني المرتبط بحسابك،\nوسنرسل لك رمزًا للتحقق من هويتك",
      "37" : "تذكرت كلمة المرور؟",
      "38" : "إرسال الرمز",
      "39" : "يرجى التحقق من بريدك الإلكتروني",
      "40" : "لقد قمنا بإرسال رمز مكون من 4 أرقام إلى بريدك الإلكتروني للتحقق من هويتك. يُرجى إدخال الرمز لإعادة تعيين كلمة المرور الخاصة بك.إذا لم تجد البريد الإلكتروني في صندوق الوارد، يُرجى التحقق من مجلد الرسائل غير المرغوب بها أو المحاولة مرة أخرى",
      "41" : "إذا لم تستلم البريد الإلكتروني، يُرجى المحاولة باستخدام",
      "42" : "بريد إلكتروني آخر"
    },
    "en" : {
      "1"  : "Choose your preferred language",
      "2"  : "Arabic",
      "3"  : "English",
      "4"  : "Welcome",
      "5"  : "Build a healthy\nlifestyle.",
      "6"  : "Track what you eat",
      "7"  : "Food",
      "8"  : "Workout anywhere",
      "9"  : "Gym, home or even the park",
      "10" : "Share experience",
      "11" : "Post & comment",
      "12" : "Sign in",
      "13" : "Sign up",
      "14" : "Welcome Back",
      "15" : "Sign in with your email and password \nor continue with social media",
      "16" : "Email",
      "17" : "Enter your email",
      "18" : "Password",
      "19" : "Enter your password",
      "20" : "Forgot password?",
      "21" : "Don't have an account? ",
      "25" : "Glad to see you",
      "26" : "Get started by creating an account,\nor use your social media profile to sign up",
      "27" : "First name",
      "28" : "Enter your first name",
      "29" : "Last name",
      "30" : "Enter your last name",
      "31" : "Confirm password",
      "32" : "Enter your password again",
      "33" : "Already have an account? ",
      "34" : "Forgot password",
      "35" : "Reset password",
      "36" : "Enter the email address linked to your account\nand we'll send an OTP code to verify your identity",
      "37" : "Remembered password?",
      "38" : "Send code",
      "39" : "Check your email",
      "40" : "We have sent a 4-digit code to your email address to verify your identity. Please enter the code to reset your password. If you don't see the email in your inbox, please check your spam folder or try again",
      "41" : "Didn't receive the email? ",
      "42" : "try another email",
    }
  };
}