import 'package:get/get.dart';

class Translate extends Translations{
  @override
  Map<String, Map<String, String>> get keys => {

    "ar" : {
      "chooseLang" : "اختر لغتك المفضلة",
      "ar" : "عربي",
      "en" : "إنجليزي",
      "welcome" : "مرحباً",
      "buildlifestyle" : "ابني نمط حياة صحي",
      "trackFood" : "تتبع ما تأكله",
      "trackFoodDesc" : "طعام",
      "workoutAnywhere" : "تمرن في أي مكان",
      "workoutAnywhereDesc" : "صالة الألعاب الرياضية أو المنزل أو حتى الحديقة",
      "shareExp" : "شارك الخبرة",
      "shareExpDesc" : "النشر والتعليق",
      "SignIn" : "تسجيل الدخول",
      "SignUp" : "إنشاء حساب",
      "welcomeBack" : "مرحبًا بعودتك",
      "SignInDesc" : "قم بتسجيل الدخول باستخدام بريدك الإلكتروني وكلمة المرور \nأو باستخدام وسائل التواصل الاجتماعي",
      "email" : "بريد إلكتروني",
      "enterEmail" : "أدخل بريدك الإلكتروني",
      "pass" : "كلمة المرور",
      "enterPass" : "أدخل كلمة المرور",
      "forgotPass" : "هل نسيت كلمة المرور؟",
      "noAcc" : "ليس لديك حساب؟ ",
      "gladToSeeu" : "نحن سعداء لرؤيتك",
      "signUpDesc" : "ابدأ الآن بإنشاء حسابك، أو استخدم ملفك الشخصي\nعلى وسائل التواصل الاجتماعي للتسجيل",
      "fname" : "الاسم الاول",
      "enterFname" : "أدخل اسمك الأول",
      "lname" : "اسم عائلتك",
      "enterLname" : "أدخل اسم عائلتك",
      "alreadySigned" : "هل سبق لك التسجيل من قبل؟ ",
      "34" : "نسيت كلمة المرور",
      "35" : "إعادة تعيين كلمة المرور",
      "36" : "أدخل عنوان البريد الإلكتروني المرتبط بحسابك،\nوسنرسل لك رمزًا للتحقق من هويتك",
      "37" : "تذكرت كلمة المرور؟",
      "38" : "إرسال الرمز",
      "39" : "يرجى التحقق من بريدك الإلكتروني",
      "40" : "لقد قمنا بإرسال رمز مكون من 4 أرقام إلى بريدك الإلكتروني للتحقق من هويتك. يُرجى إدخال الرمز لإعادة تعيين كلمة المرور الخاصة بك.إذا لم تجد البريد الإلكتروني في صندوق الوارد، يُرجى التحقق من مجلد الرسائل غير المرغوب بها أو المحاولة مرة أخرى",
      "41" : "إذا لم تستلم البريد الإلكتروني، يُرجى المحاولة باستخدام",
      "42" : "بريد إلكتروني آخر",

      "hello" : "مرحباً",
  "calories": "السعرات الحرارية",
  "trackCalories": "تتبع سعراتك الحرارية\nوحقق هدفك اليومي!",
  "exercises" : "تمارين",
  "exercisesDesc" : "تدرب على أجزاء مختلفة من\nجسمك لتحقيق الجسم الذي\nتحلم به",
  "nutrition" : "تغذية",
  "nutritionDesc" : "تتبع ما تأكله",
  "feed" : "المنشورات",
  "feedDesc" : "انضم إلى المجتمع الإلكتروني\nواطّلع على مقالاتنا الجديدة.",
  "home" : "الصفحة الرئيسية",
  "favorite" : "المفضلة",
  "profile" : "الملف الشخصي",
  "settings" : "الإعدادات",
  "searchFood" : "ابحث عن طعام",
  "kcal" : "سعرة حرارية ⋅ 100 جم",
  "kcal2" : "سعرة حرارية",
  "carbs" : "الكربوهيدرات",
  "fats" : "الدهون",
  "protein" : "البروتين",
  "bowl" : "الوعاء",
  "macros" : "المكونات الغذائية لكل 100 جم",
  "enterAmount" : "أدخل الكمية بالجرام",
  "example" : "مثال: 100",
  "addBowl" : "أضف إلى الوعاء",
  "highRisk" : "بناءً على حساسياتك وأمراضك، يُعتبر هذا الطعام ذو مخاطر عالية",
  "medRisk" : "بناءً على حساسياتك وأمراضك، يُعتبر هذا الطعام ذو مخاطر متوسطة",
  "lowRisk" : "بناءً على حساسياتك وأمراضك، يُعتبر هذا الطعام ذو مخاطر منخفضة",
  "noRisk" : "بناءً على حساسياتك وأمراضك، لا يُعتبر هذا الطعام ذو مخاطر",
  "diff" : "الصعوبة",
  "summary" : "ملخص الوعاء",
  "totalCalories" : "إجمالي السعرات الحرارية",
  "totalCarbohydrates" : "إجمالي الكربوهيدرات",
  "totalFats" : "إجمالي الدهون",
  "totalProtein" : "إجمالي البروتين",
  "unit" : " جم",
  "eat" : "تناول!",
  "goal" : "هدفك",
  "gain" : "زيادة الوزن",
  "maintain" : "الحفاظ على الوزن",
  "lose" : "خسارة الوزن",
  "anthropometry" : "أبعاد الجسم",
  "male" : "ذكر",
  "female" : "أنثى",
  "height" : "الطول (بالسنتيمتر)",
  "weight" : "الوزن (بالكيلوجرام)",
  "age" : "العمر",
  "activity" : "مستوى النشاط اليومي",
  "sedentary" : "غير نشط (قليل أو لا تمارس التمارين)",
  "lightly" : "نشاط طفيف (ممارسة رياضة خفيفة أو رياضة مرة إلى ثلاث مرات في الأسبوع)",
  "moderately" : "نشاط معتدل (ممارسة رياضة متوسطة أو رياضة ثلاث مرات إلى خمس مرات في الأسبوع)",
  "very" : "نشاط مكثف (ممارسة رياضة شاقة أو رياضة ستة أو سبع مرات في الأسبوع)",
  "extra" : "نشاط إضافي (ممارسة رياضة شاقة جداً أو العمل في وظيفة تتطلب جهدًا بدنيًا)",
  "allergyIllness" : "الحساسية والأمراض",
  "diabetes" : "مرض السكري من النوع 2",
  "hypertension" : "ارتفاع ضغط الدم",
  "celiac" : "مرض السيلياك",
  "wheat" : "حساسية القمح",
  "milk" : "حساسية الحليب",
  "tdee" : "حساب TDEE",
  "unit2" : "جرام"
    },
    "en" : {
      "chooseLang"  : "Choose your preferred language",
      "ar"  : "Arabic",
      "en"  : "English",
      "welcome"  : "Welcome!",
      "buildlifestyle"  : "Build a healthy\nlifestyle.",
      "trackFood"  : "Track what you eat",
      "trackFoodDesc"  : "Food",
      "workoutAnywhere"  : "Workout anywhere",
      "workoutAnywhereDesc"  : "Gym, home or even the park",
      "shareExp" : "Share experience",
      "shareExpDesc" : "Post & comment",
      "SignIn" : "Sign in",
      "SignUp" : "Sign up",
      "welcomeBack" : "Welcome Back",
      "SignInDesc" : "Sign in with your email and password \nor continue with social media",
      "email" : "Email",
      "enterEmail" : "Enter your email",
      "pass" : "Password",
      "enterPass" : "Enter your password",
      "forgotPass" : "Forgot password?",
      "noAcc" : "Don't have an account? ",
      "gladToSeeu" : "Glad to see you",
      "signUpDesc" : "Get started by creating an account,\nor use your social media profile to sign up",
      "fname" : "First name",
      "enterFname" : "Enter your first name",
      "lname" : "Last name",
      "enterLname" : "Enter your last name",
      "alreadySigned" : "Already have an account? ",
      "34" : "Forgot password",
      "35" : "Reset password",
      "36" : "Enter the email address linked to your account\nand we'll send an OTP code to verify your identity",
      "37" : "Remembered password?",
      "38" : "Send code",
      "39" : "Check your email",
      "40" : "We have sent a 4-digit code to your email address to verify your identity. Please enter the code to reset your password. If you don't see the email in your inbox, please check your spam folder or try again",
      "41" : "Didn't receive the email? ",
      "42" : "try another email",
      

      "hello" : "Hello",
      "calories": "Calories",
      "trackCalories": "Track your calories and\nkeep up with your daily goal!",
      "exercises" : "Exercises",
      "exercisesDesc" : "Train different parts of your\nbody to achieve your dream\nphysique",
      "nutrition" : "Nutrition",
      "nutritionDesc" : "Track what you eat",
      "feed" : "Feed",
      "feedDesc" : "Join the online community\nand read our new posts.",
      "home" : "Home",
      "favorite" : "Favorites",
      "profile" : "Profile",
      "settings" : "Settings",
      "searchFood" : "Search for food",
      "kcal" : " Kcal ⋅ 100g",
      "kcal2" : " Kcal",
      "carbs" : "Carbs",
      "fats" : "Fats",
      "protein" : "Protein",
      "bowl" : "Bowl",
      "macros" : "MACROS PER 100G",
      "enterAmount" : "Enter amount in grams",
      "example" : "e.g., 100",
      "addBowl" : "Add to bowl",
      "highRisk" : "Based on your allergies & illnesses this food is considered high risk",
      "medRisk" : "Based on your allergies & illnesses this food is considered medium risk",
      "lowRisk" : "Based on your allergies & illnesses this food is considered low risk",
      "noRisk" : "Based on your allergies & illnesses this food is considered no risk",
      "diff" : "Difficulty",
      "summary" : "Bowl Summary",
      "totalCalories" : "Total Calories",
      "totalCarbohydrates" : "Total Carbohydrates",
      "totalFats" : "Total Fats",
      "totalProtein" : "Total Protein",
      "unit" : " g",
      "eat" : "Eat!",
      "goal" : "Your goal",
      "gain" : "Gain Weight",
      "maintain" : "Maintain Weight",
      "lose" : "Lose Weight",
      "anthropometry" : "Body anthropometry",
      "male" : "Male",
      "female" : "Female",
      "height" : "Height (in cm)",
      "weight" : "weight (in kg)",
      "age" : "Age",
      "activity" : "Daily activity level",
      "sedentary" : "Sedentary (little to no exercise)",
      "lightly" : "Lightly active (light exercise or sports 1-3 days a week)",
      "moderately" : "Moderately active (moderate exercise orsports 3-5 days a week)",
      "very" : "Very active (hard exercise or sports 6-7 days a week)",
      "extra" : "Extra active (very hard exercise or a physically demanding job)",
      "allergyIllness" : "Allergy & Illness",
      "diabetes" : "Type 2 Diabetes",
      "hypertension" : "Hypertension",
      "celiac" : "Celiac Disease",
      "wheat" : "Wheat Allergy",
      "milk" : "Milk Allergy",
      "tdee" : "Calculate TDEE",
      "unit2" : "grams"

      //"allergy" : ""

    }
  };
}